import type {
  UserProfile,
  LeaveBalance,
  LeaveRequest,
  AuditEntry,
  LeaveTypeConfig,
  AuditAction,
} from '@/components/lms/types';

export const LEAVE_TYPES: LeaveTypeConfig[] = [
  { id: 'lt-1', name: 'Annual Leave', defaultDays: 15, allowCarryover: true, isActive: true },
  { id: 'lt-2', name: 'Sick Leave', defaultDays: 10, allowCarryover: false, isActive: true },
  { id: 'lt-3', name: 'Emergency Leave', defaultDays: 3, allowCarryover: false, isActive: true },
  { id: 'lt-4', name: 'Unpaid Leave', defaultDays: 0, allowCarryover: false, isActive: true },
  { id: 'lt-5', name: 'Paternity/Maternity Leave', defaultDays: 60, allowCarryover: false, isActive: true },
];

export const CURRENT_USER_EMPLOYEE: UserProfile = {
  id: 'emp-001',
  email: 'miguel.santos@stratpoint.com',
  fullName: 'Miguel Santos',
  role: 'employee',
  managerId: 'mgr-001',
  managerName: 'Ana Reyes',
  department: 'Engineering',
  office: 'Makati HQ',
  initials: 'MS',
};

export const CURRENT_USER_MANAGER: UserProfile = {
  id: 'mgr-001',
  email: 'ana.reyes@stratpoint.com',
  fullName: 'Ana Reyes',
  role: 'manager',
  managerId: 'dir-001',
  managerName: 'Roberto Cruz',
  department: 'Engineering',
  office: 'Makati HQ',
  initials: 'AR',
};

export const CURRENT_USER_HR: UserProfile = {
  id: 'hr-001',
  email: 'carmen.ortiz@stratpoint.com',
  fullName: 'Carmen Ortiz',
  role: 'hr_admin',
  department: 'Human Resources',
  office: 'Makati HQ',
  initials: 'CO',
};

export const CURRENT_USER_SYSADMIN: UserProfile = {
  id: 'sys-001',
  email: 'joel.reyes@stratpoint.com',
  fullName: 'Joel Reyes',
  role: 'sys_admin',
  department: 'IT',
  office: 'Makati HQ',
  initials: 'JR',
};

export const EMPLOYEE_BALANCES: LeaveBalance[] = [
  { leaveType: 'Annual Leave', total: 15, used: 3, remaining: 12 },
  { leaveType: 'Sick Leave', total: 10, used: 2, remaining: 8 },
  { leaveType: 'Emergency Leave', total: 3, used: 1, remaining: 2 },
  { leaveType: 'Unpaid Leave', total: 0, used: 0, remaining: 0 },
  { leaveType: 'Paternity/Maternity Leave', total: 60, used: 0, remaining: 60 },
];

export const MY_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'LR-2026-0042',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Annual Leave',
    startDate: '2026-06-16',
    endDate: '2026-06-18',
    days: 3,
    reason: 'Family vacation to Palawan with wife and kids. We have pre-booked flights and accommodations.',
    status: 'PENDING',
    submittedDate: '2026-06-04',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0031',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Sick Leave',
    startDate: '2026-05-12',
    endDate: '2026-05-13',
    days: 2,
    reason: 'Flu and fever with doctor\'s advice to rest. Attached medical certificate.',
    status: 'APPROVED',
    submittedDate: '2026-05-12',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    managerNote: 'Approved. Get well soon!',
    hasDocument: true,
  },
  {
    id: 'LR-2026-0018',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Annual Leave',
    startDate: '2026-04-07',
    endDate: '2026-04-09',
    days: 3,
    reason: 'Holy Week family gathering in Batangas.',
    status: 'APPROVED',
    submittedDate: '2026-03-28',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    managerNote: 'Approved. Enjoy the holiday!',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0009',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Emergency Leave',
    startDate: '2026-02-20',
    endDate: '2026-02-20',
    days: 1,
    reason: 'Father was hospitalized due to cardiac episode. Need to be present at the hospital.',
    status: 'REJECTED',
    submittedDate: '2026-02-20',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    rejectionReason: 'Emergency Leave is reserved for immediate family emergencies. Please use Annual Leave instead. Please resubmit using Annual Leave.',
    hasDocument: false,
  },
];

export const PENDING_APPROVALS: LeaveRequest[] = [
  {
    id: 'LR-2026-0042',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Annual Leave',
    startDate: '2026-06-16',
    endDate: '2026-06-18',
    days: 3,
    reason: 'Family vacation to Palawan with wife and kids. We have pre-booked flights and accommodations.',
    status: 'PENDING',
    submittedDate: '2026-06-04',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0040',
    employeeId: 'emp-002',
    employeeName: 'Sofia Lim',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Sick Leave',
    startDate: '2026-06-08',
    endDate: '2026-06-09',
    days: 2,
    reason: 'Severe migraine and vertigo. Unable to work. Will consult doctor tomorrow.',
    status: 'PENDING',
    submittedDate: '2026-06-05',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    hasDocument: true,
  },
  {
    id: 'LR-2026-0038',
    employeeId: 'emp-003',
    employeeName: 'Carlo Mendoza',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Emergency Leave',
    startDate: '2026-06-06',
    endDate: '2026-06-06',
    days: 1,
    reason: 'Mother-in-law passed away unexpectedly. Need to assist with funeral arrangements.',
    status: 'PENDING',
    submittedDate: '2026-06-05',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0045',
    employeeId: 'emp-005',
    employeeName: 'Jose Tan',
    department: 'Engineering',
    office: 'Cebu',
    leaveType: 'Paternity/Maternity Leave',
    startDate: '2026-07-01',
    endDate: '2026-08-29',
    days: 60,
    reason: 'Paternity leave for birth of first child. Due date is June 28.',
    status: 'PENDING',
    submittedDate: '2026-06-01',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    hasDocument: true,
  },
];

export const ALL_REQUESTS: LeaveRequest[] = [
  ...PENDING_APPROVALS,
  {
    id: 'LR-2026-0036',
    employeeId: 'emp-004',
    employeeName: 'Isabel Cruz',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Annual Leave',
    startDate: '2026-06-23',
    endDate: '2026-06-27',
    days: 5,
    reason: 'Summer vacation trip to Japan. Non-refundable flights and hotels booked.',
    status: 'APPROVED',
    submittedDate: '2026-05-20',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    managerNote: 'Approved. Enjoy your trip!',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0031',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Sick Leave',
    startDate: '2026-05-12',
    endDate: '2026-05-13',
    days: 2,
    reason: 'Flu and fever with doctor\'s advice to rest.',
    status: 'APPROVED',
    submittedDate: '2026-05-12',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    managerNote: 'Approved. Get well soon!',
    hasDocument: true,
  },
  {
    id: 'LR-2026-0028',
    employeeId: 'fin-001',
    employeeName: 'Maria Garcia',
    department: 'Finance',
    office: 'Cebu',
    leaveType: 'Annual Leave',
    startDate: '2026-05-26',
    endDate: '2026-05-30',
    days: 5,
    reason: 'Annual family reunion in Iloilo.',
    status: 'APPROVED',
    submittedDate: '2026-05-10',
    managerId: 'mgr-002',
    managerName: 'Benjamin Wong',
    managerNote: 'Approved. Have a great time with family.',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0022',
    employeeId: 'emp-005',
    employeeName: 'Jose Tan',
    department: 'Engineering',
    office: 'Cebu',
    leaveType: 'Unpaid Leave',
    startDate: '2026-05-05',
    endDate: '2026-05-08',
    days: 4,
    reason: 'Personal matter requiring extended leave beyond available balance.',
    status: 'REJECTED',
    submittedDate: '2026-04-28',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    rejectionReason: 'Sprint 6 critical delivery period. Cannot approve team leave during final integration week. Please reschedule to post-release window starting June 2026.',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0018',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Annual Leave',
    startDate: '2026-04-07',
    endDate: '2026-04-09',
    days: 3,
    reason: 'Holy Week family gathering.',
    status: 'APPROVED',
    submittedDate: '2026-03-28',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    managerNote: 'Approved. Enjoy the holiday!',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0014',
    employeeId: 'ops-001',
    employeeName: 'Ramon dela Cruz',
    department: 'Operations',
    office: 'Davao',
    leaveType: 'Sick Leave',
    startDate: '2026-04-02',
    endDate: '2026-04-03',
    days: 2,
    reason: 'Dengue fever, hospitalized. Medical certificate attached.',
    status: 'APPROVED',
    submittedDate: '2026-04-02',
    managerId: 'mgr-003',
    managerName: 'Rosa Villareal',
    managerNote: 'Approved. Rest well, Ramon.',
    hasDocument: true,
  },
  {
    id: 'LR-2026-0009',
    employeeId: 'emp-001',
    employeeName: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Emergency Leave',
    startDate: '2026-02-20',
    endDate: '2026-02-20',
    days: 1,
    reason: 'Father was hospitalized.',
    status: 'REJECTED',
    submittedDate: '2026-02-20',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    rejectionReason: 'Please resubmit using Annual Leave for this type of family situation.',
    hasDocument: false,
  },
  {
    id: 'LR-2026-0005',
    employeeId: 'emp-002',
    employeeName: 'Sofia Lim',
    department: 'Engineering',
    office: 'Makati HQ',
    leaveType: 'Annual Leave',
    startDate: '2026-02-10',
    endDate: '2026-02-12',
    days: 3,
    reason: 'Valentine\'s Day trip to Bohol.',
    status: 'CANCELLED',
    submittedDate: '2026-02-01',
    managerId: 'mgr-001',
    managerName: 'Ana Reyes',
    hasDocument: false,
  },
];

const auditActions: AuditAction[] = ['SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'OVERRIDDEN'];

export const AUDIT_LOG: AuditEntry[] = [
  {
    id: 'aud-001',
    timestamp: '2026-06-05T08:32:14Z',
    actorName: 'Miguel Santos',
    actorId: 'emp-001',
    action: 'SUBMITTED',
    recordId: 'LR-2026-0042',
    tableName: 'leaves',
    oldData: {},
    newData: {
      id: 'LR-2026-0042',
      employee_id: 'emp-001',
      leave_type: 'Annual Leave',
      start_date: '2026-06-16',
      end_date: '2026-06-18',
      status: 'PENDING',
      days: 3,
    },
  },
  {
    id: 'aud-002',
    timestamp: '2026-06-05T09:15:47Z',
    actorName: 'Sofia Lim',
    actorId: 'emp-002',
    action: 'SUBMITTED',
    recordId: 'LR-2026-0040',
    tableName: 'leaves',
    oldData: {},
    newData: {
      id: 'LR-2026-0040',
      employee_id: 'emp-002',
      leave_type: 'Sick Leave',
      start_date: '2026-06-08',
      end_date: '2026-06-09',
      status: 'PENDING',
      days: 2,
    },
  },
  {
    id: 'aud-003',
    timestamp: '2026-06-05T10:02:33Z',
    actorName: 'Carlo Mendoza',
    actorId: 'emp-003',
    action: 'SUBMITTED',
    recordId: 'LR-2026-0038',
    tableName: 'leaves',
    oldData: {},
    newData: {
      id: 'LR-2026-0038',
      employee_id: 'emp-003',
      leave_type: 'Emergency Leave',
      start_date: '2026-06-06',
      end_date: '2026-06-06',
      status: 'PENDING',
      days: 1,
    },
  },
  {
    id: 'aud-004',
    timestamp: '2026-06-01T14:20:00Z',
    actorName: 'Jose Tan',
    actorId: 'emp-005',
    action: 'SUBMITTED',
    recordId: 'LR-2026-0045',
    tableName: 'leaves',
    oldData: {},
    newData: {
      id: 'LR-2026-0045',
      employee_id: 'emp-005',
      leave_type: 'Paternity/Maternity Leave',
      start_date: '2026-07-01',
      end_date: '2026-08-29',
      status: 'PENDING',
      days: 60,
    },
  },
  {
    id: 'aud-005',
    timestamp: '2026-05-21T11:44:09Z',
    actorName: 'Ana Reyes',
    actorId: 'mgr-001',
    action: 'APPROVED',
    recordId: 'LR-2026-0036',
    tableName: 'leaves',
    oldData: { status: 'PENDING', manager_note: null },
    newData: {
      status: 'APPROVED',
      manager_note: 'Approved. Enjoy your trip!',
    },
  },
  {
    id: 'aud-006',
    timestamp: '2026-05-13T08:05:22Z',
    actorName: 'Ana Reyes',
    actorId: 'mgr-001',
    action: 'APPROVED',
    recordId: 'LR-2026-0031',
    tableName: 'leaves',
    oldData: { status: 'PENDING' },
    newData: { status: 'APPROVED', manager_note: 'Get well soon!' },
  },
  {
    id: 'aud-007',
    timestamp: '2026-04-29T14:30:51Z',
    actorName: 'Ana Reyes',
    actorId: 'mgr-001',
    action: 'REJECTED',
    recordId: 'LR-2026-0022',
    tableName: 'leaves',
    oldData: { status: 'PENDING' },
    newData: {
      status: 'REJECTED',
      rejection_reason:
        'Sprint 6 critical delivery period. Cannot approve team leave during final integration week.',
    },
  },
  {
    id: 'aud-008',
    timestamp: '2026-04-15T09:00:00Z',
    actorName: 'Carmen Ortiz',
    actorId: 'hr-001',
    action: 'OVERRIDDEN',
    recordId: 'LR-2026-0009',
    tableName: 'leaves',
    oldData: { status: 'REJECTED' },
    newData: {
      status: 'APPROVED',
      override_reason:
        'HR override: Employee provided hospital record post-facto. Emergency Leave category confirmed valid per policy clarification from HR Director.',
    },
  },
  {
    id: 'aud-009',
    timestamp: '2026-02-12T16:20:05Z',
    actorName: 'Sofia Lim',
    actorId: 'emp-002',
    action: 'CANCELLED',
    recordId: 'LR-2026-0005',
    tableName: 'leaves',
    oldData: { status: 'PENDING' },
    newData: { status: 'CANCELLED' },
  },
  {
    id: 'aud-010',
    timestamp: '2026-01-15T08:00:00Z',
    actorName: 'Carmen Ortiz',
    actorId: 'hr-001',
    action: 'OVERRIDDEN',
    recordId: 'BAL-2026-RESET',
    tableName: 'leave_balances',
    oldData: { year: 2025, total_days: 15, used_days: 9 },
    newData: { year: 2026, total_days: 15, used_days: 0 },
  },
];

export const ALL_EMPLOYEES_BALANCES = [
  {
    id: 'emp-001',
    name: 'Miguel Santos',
    department: 'Engineering',
    office: 'Makati HQ',
    annualLeave: { total: 15, used: 3 },
    sickLeave: { total: 10, used: 2 },
    emergencyLeave: { total: 3, used: 1 },
    unpaidLeave: { total: 0, used: 0 },
    maternityLeave: { total: 60, used: 0 },
  },
  {
    id: 'emp-002',
    name: 'Sofia Lim',
    department: 'Engineering',
    office: 'Makati HQ',
    annualLeave: { total: 15, used: 5 },
    sickLeave: { total: 10, used: 0 },
    emergencyLeave: { total: 3, used: 0 },
    unpaidLeave: { total: 0, used: 0 },
    maternityLeave: { total: 60, used: 0 },
  },
  {
    id: 'emp-003',
    name: 'Carlo Mendoza',
    department: 'Engineering',
    office: 'Makati HQ',
    annualLeave: { total: 15, used: 15 },
    sickLeave: { total: 10, used: 4 },
    emergencyLeave: { total: 3, used: 1 },
    unpaidLeave: { total: 0, used: 0 },
    maternityLeave: { total: 60, used: 0 },
  },
  {
    id: 'emp-004',
    name: 'Isabel Cruz',
    department: 'Engineering',
    office: 'Makati HQ',
    annualLeave: { total: 15, used: 10 },
    sickLeave: { total: 10, used: 1 },
    emergencyLeave: { total: 3, used: 0 },
    unpaidLeave: { total: 0, used: 0 },
    maternityLeave: { total: 60, used: 0 },
  },
  {
    id: 'emp-005',
    name: 'Jose Tan',
    department: 'Engineering',
    office: 'Cebu',
    annualLeave: { total: 15, used: 12 },
    sickLeave: { total: 10, used: 3 },
    emergencyLeave: { total: 3, used: 2 },
    unpaidLeave: { total: 0, used: 4 },
    maternityLeave: { total: 60, used: 60 },
  },
  {
    id: 'fin-001',
    name: 'Maria Garcia',
    department: 'Finance',
    office: 'Cebu',
    annualLeave: { total: 15, used: 8 },
    sickLeave: { total: 10, used: 0 },
    emergencyLeave: { total: 3, used: 1 },
    unpaidLeave: { total: 0, used: 0 },
    maternityLeave: { total: 60, used: 0 },
  },
  {
    id: 'ops-001',
    name: 'Ramon dela Cruz',
    department: 'Operations',
    office: 'Davao',
    annualLeave: { total: 15, used: 15 },
    sickLeave: { total: 10, used: 2 },
    emergencyLeave: { total: 3, used: 0 },
    unpaidLeave: { total: 0, used: 0 },
    maternityLeave: { total: 60, used: 0 },
  },
  {
    id: 'mkt-001',
    name: 'Rosa Villareal',
    department: 'Marketing',
    office: 'Davao',
    annualLeave: { total: 15, used: 7 },
    sickLeave: { total: 10, used: 1 },
    emergencyLeave: { total: 3, used: 0 },
    unpaidLeave: { total: 0, used: 0 },
    maternityLeave: { total: 60, used: 0 },
  },
];

export interface Notification {
  id: string;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  read: boolean;
  createdAt: string;
  linkTo?: string;
}

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    title: 'Leave Approved',
    message: 'Your Annual Leave request (Mar 10-14) has been approved by Ana Reyes.',
    type: 'success',
    read: false,
    createdAt: '2026-02-21T10:00:00Z',
    linkTo: '/my-requests/lr-001',
  },
  {
    id: 'notif-002',
    title: 'Leave Rejected',
    message: 'Your Emergency Leave request (Feb 5) has been rejected by Ana Reyes.',
    type: 'error',
    read: true,
    createdAt: '2026-02-04T16:30:00Z',
    linkTo: '/my-requests/lr-004',
  },
  {
    id: 'notif-003',
    title: 'New Leave Request',
    message: 'Carlo Mendoza has submitted a new Emergency Leave request.',
    type: 'info',
    read: false,
    createdAt: '2026-06-05T10:02:33Z',
    linkTo: '/approvals/lr-0038',
  },
  {
    id: 'notif-004',
    title: 'Paternity Leave Filed',
    message: 'Jose Tan has submitted a Paternity Leave request (60 days starting Jul 1).',
    type: 'info',
    read: false,
    createdAt: '2026-06-01T14:20:00Z',
    linkTo: '/approvals/lr-0045',
  },
  {
    id: 'notif-005',
    title: 'Balance Updated',
    message: 'Your Sick Leave balance has been updated. 8 days remaining.',
    type: 'warning',
    read: false,
    createdAt: '2026-04-18T11:00:00Z',
  },
];
